import { app } from 'electron'
import fs from 'node:fs'
import path from 'node:path'

/**
 * Everything the launcher ever writes lives under this one folder:
 *   %APPDATA%\Launchpad\
 * (Safety Rule 4). No other location is ever written to.
 */
export const APP_FOLDER_NAME = 'Launchpad'
/** Folder name used by builds before the rename; moved to APP_FOLDER_NAME on first start. */
export const LEGACY_FOLDER_NAME = 'PersonalLauncher'

export interface Paths {
  dataDir: string
  dbFile: string
  assetsDir: string
  snapshotsDir: string
}

let cached: Paths | null = null

/**
 * Picks the data folder inside appData. If only the legacy folder exists it is
 * renamed in place (same drive, atomic); if that fails — e.g. an old instance
 * still has it open — the legacy folder keeps being used. Nothing is copied
 * or deleted.
 */
export function resolveDataDir(appData: string): string {
  const target = path.join(appData, APP_FOLDER_NAME)
  const legacy = path.join(appData, LEGACY_FOLDER_NAME)
  if (!fs.existsSync(target) && fs.existsSync(legacy)) {
    try {
      fs.renameSync(legacy, target)
    } catch {
      return legacy
    }
  }
  return target
}

/** Must run before app 'ready' so Electron itself also uses the folder. */
export function configureUserData(): void {
  app.setName(APP_FOLDER_NAME)
  app.setPath('userData', resolveDataDir(app.getPath('appData')))
}

export function getPaths(): Paths {
  if (cached) return cached
  const dataDir = app.getPath('userData')
  const paths: Paths = {
    dataDir,
    dbFile: path.join(dataDir, 'launcher.db'),
    assetsDir: path.join(dataDir, 'assets'),
    snapshotsDir: path.join(dataDir, 'snapshots')
  }
  fs.mkdirSync(paths.assetsDir, { recursive: true })
  fs.mkdirSync(paths.snapshotsDir, { recursive: true })
  cached = paths
  return paths
}

/** Asset filenames are always generated by us: a UUID plus a known image extension. */
export const ASSET_FILENAME_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(png|jpg|jpeg|webp)$/

/**
 * Turns an asset filename into an absolute path, but only if it is a plain
 * generated filename that resolves to a file directly inside the assets folder.
 * Anything else (traversal, absolute paths, odd names) yields null.
 */
export function resolveInsideAssets(fileName: unknown): string | null {
  if (typeof fileName !== 'string' || !ASSET_FILENAME_RE.test(fileName)) return null
  const { assetsDir } = getPaths()
  const resolved = path.resolve(assetsDir, fileName)
  if (path.dirname(resolved) !== path.resolve(assetsDir)) return null
  return resolved
}
