import { app } from 'electron'
import fs from 'node:fs'
import path from 'node:path'

/**
 * Everything the launcher ever writes lives under this one folder:
 *   %APPDATA%\PersonalLauncher\
 * (Safety Rule 4). No other location is ever written to.
 */
export const APP_FOLDER_NAME = 'PersonalLauncher'

export interface Paths {
  dataDir: string
  dbFile: string
  assetsDir: string
  snapshotsDir: string
}

let cached: Paths | null = null

/** Must run before app 'ready' so Electron itself also uses the folder. */
export function configureUserData(): void {
  app.setName(APP_FOLDER_NAME)
  app.setPath('userData', path.join(app.getPath('appData'), APP_FOLDER_NAME))
}

export function getPaths(): Paths {
  if (cached) return cached
  const dataDir = app.getPath('userData')
  const paths: Paths = {
    dataDir,
    dbFile: path.join(dataDir, 'launcher.db'),
    assetsDir: path.join(dataDir, 'assets'),
    snapshotsDir: path.join(dataDir, 'snapshots')
  }
  fs.mkdirSync(paths.assetsDir, { recursive: true })
  fs.mkdirSync(paths.snapshotsDir, { recursive: true })
  cached = paths
  return paths
}

/** Asset filenames are always generated by us: a UUID plus a known image extension. */
export const ASSET_FILENAME_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(png|jpg|jpeg|webp)$/

/**
 * Turns an asset filename into an absolute path, but only if it is a plain
 * generated filename that resolves to a file directly inside the assets folder.
 * Anything else (traversal, absolute paths, odd names) yields null.
 */
export function resolveInsideAssets(fileName: unknown): string | null {
  if (typeof fileName !== 'string' || !ASSET_FILENAME_RE.test(fileName)) return null
  const { assetsDir } = getPaths()
  const resolved = path.resolve(assetsDir, fileName)
  if (path.dirname(resolved) !== path.resolve(assetsDir)) return null
  return resolved
}
